package drawingStyles.forms;

import drawingStyles.MapObjectDrawSettings;

/**
 * Dialog for editing map object draw style
 *
 * @author pgalex
 */
public class JDialogEditMapObjectDrawSettings extends javax.swing.JDialog
{
	/**
	 * map object draw setting, editing with dialog
	 */
	private MapObjectDrawSettings editingMapObjectDrawSettings;

	/**
	 * Creates dialog for editing map object draw style
	 *
	 * @param parent parent frame
	 * @param modal show as modal
	 * @param drawSettingsToEdit map object draw setting, that will be editing
	 * with dialog
	 * @throws IllegalArgumentException editing map object draw setting is null
	 */
	public JDialogEditMapObjectDrawSettings(java.awt.Frame parent, boolean modal,
					MapObjectDrawSettings drawSettingsToEdit) throws IllegalArgumentException
	{
		super(parent, modal);

		if (drawSettingsToEdit == null)
		{
			throw new IllegalArgumentException();
		}

		initComponents();

		editingMapObjectDrawSettings = drawSettingsToEdit;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabelDescription = new javax.swing.JLabel();
    jTextFieldDescription = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabelDescription.setText("Description");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLabelDescription)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jTextFieldDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 303, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(118, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(15, 15, 15)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabelDescription)
          .add(jTextFieldDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(395, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabelDescription;
  private javax.swing.JTextField jTextFieldDescription;
  // End of variables declaration//GEN-END:variables
}
