/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author abc
 */
public class JDialogEditMapObjects extends javax.swing.JDialog
{
	/**
	 * Creates new form JDialogEditMapObjects
	 *
	 * @param parent
	 * @param modal
	 */
	public JDialogEditMapObjects(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();
		
		setLocationRelativeTo(parent);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelObjects = new javax.swing.JPanel();
        jComboBoxObjects = new javax.swing.JComboBox();
        jButtonAdd = new javax.swing.JButton();
        jButtonAddByCopy = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanelDialogControls = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jPanelObjectsDrawPriority = new javax.swing.JPanel();
        list1 = new java.awt.List();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemFileOpen = new javax.swing.JMenuItem();
        jMenuItemFileSave = new javax.swing.JMenuItem();
        jMenuItemFileSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFileExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Объекты на карте");
        setMinimumSize(new java.awt.Dimension(375, 390));

        jPanelObjects.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Объекты"));
        jPanelObjects.setMinimumSize(new java.awt.Dimension(250, 100));

        jButtonAdd.setText("Добавить");

        jButtonAddByCopy.setText("Добавить копию");

        jButtonEdit.setText("Редактировать");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jLabel1.setText("Найти:");

        javax.swing.GroupLayout jPanelObjectsLayout = new javax.swing.GroupLayout(jPanelObjects);
        jPanelObjects.setLayout(jPanelObjectsLayout);
        jPanelObjectsLayout.setHorizontalGroup(
            jPanelObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelObjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelObjectsLayout.createSequentialGroup()
                        .addComponent(jComboBoxObjects, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelObjectsLayout.createSequentialGroup()
                        .addGroup(jPanelObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelObjectsLayout.createSequentialGroup()
                                .addComponent(jButtonEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddByCopy)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelObjectsLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1)))
                        .addGap(10, 10, 10))))
        );
        jPanelObjectsLayout.setVerticalGroup(
            jPanelObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelObjectsLayout.createSequentialGroup()
                .addGroup(jPanelObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxObjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonAddByCopy)
                    .addComponent(jButtonEdit))
                .addContainerGap())
        );

        jButtonClose.setLabel("Закрыть");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDialogControlsLayout = new javax.swing.GroupLayout(jPanelDialogControls);
        jPanelDialogControls.setLayout(jPanelDialogControlsLayout);
        jPanelDialogControlsLayout.setHorizontalGroup(
            jPanelDialogControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDialogControlsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClose)
                .addContainerGap())
        );
        jPanelDialogControlsLayout.setVerticalGroup(
            jPanelDialogControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDialogControlsLayout.createSequentialGroup()
                .addComponent(jButtonClose)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanelObjectsDrawPriority.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Приоритет отрисовки"));
        jPanelObjectsDrawPriority.setMinimumSize(new java.awt.Dimension(250, 143));

        javax.swing.GroupLayout jPanelObjectsDrawPriorityLayout = new javax.swing.GroupLayout(jPanelObjectsDrawPriority);
        jPanelObjectsDrawPriority.setLayout(jPanelObjectsDrawPriorityLayout);
        jPanelObjectsDrawPriorityLayout.setHorizontalGroup(
            jPanelObjectsDrawPriorityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelObjectsDrawPriorityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelObjectsDrawPriorityLayout.setVerticalGroup(
            jPanelObjectsDrawPriorityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelObjectsDrawPriorityLayout.createSequentialGroup()
                .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuFile.setText("Файл");

        jMenuItemFileOpen.setText("Открыть ...");
        jMenuFile.add(jMenuItemFileOpen);

        jMenuItemFileSave.setText("Сохранить");
        jMenuFile.add(jMenuItemFileSave);

        jMenuItemFileSaveAs.setText("Сохранить как ...");
        jMenuItemFileSaveAs.setToolTipText("");
        jMenuFile.add(jMenuItemFileSaveAs);
        jMenuFile.add(jSeparator1);

        jMenuItemFileExit.setText("Закрыть");
        jMenuItemFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileExit);

        jMenuBarMain.add(jMenuFile);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDialogControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelObjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelObjectsDrawPriority, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelObjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelObjectsDrawPriority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDialogControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jMenuItemFileExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemFileExitActionPerformed
	{//GEN-HEADEREND:event_jMenuItemFileExitActionPerformed
		setVisible(false);
		dispose();
	}//GEN-LAST:event_jMenuItemFileExitActionPerformed
	
	private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCloseActionPerformed
	{//GEN-HEADEREND:event_jButtonCloseActionPerformed
		jMenuItemFileExitActionPerformed(evt);
	}//GEN-LAST:event_jButtonCloseActionPerformed
	
	private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEditActionPerformed
	{//GEN-HEADEREND:event_jButtonEditActionPerformed
		JDialogEditMapObjectStyle editObjectStyleDialog = new JDialogEditMapObjectStyle(null, true);
		editObjectStyleDialog.setVisible(true);
	}//GEN-LAST:event_jButtonEditActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(JDialogEditMapObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(JDialogEditMapObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(JDialogEditMapObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(JDialogEditMapObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the dialog
		 */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			@Override
			public void run()
			{
				JDialogEditMapObjects dialog = new JDialogEditMapObjects(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter()
				{
					@Override
					public void windowClosing(java.awt.event.WindowEvent e)
					{
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddByCopy;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JComboBox jComboBoxObjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemFileExit;
    private javax.swing.JMenuItem jMenuItemFileOpen;
    private javax.swing.JMenuItem jMenuItemFileSave;
    private javax.swing.JMenuItem jMenuItemFileSaveAs;
    private javax.swing.JPanel jPanelDialogControls;
    private javax.swing.JPanel jPanelObjects;
    private javax.swing.JPanel jPanelObjectsDrawPriority;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
