package forms;

import drawingStyles.MapObjectDrawSettings;
import java.awt.Window;
import map.MapObject;

/**
 * Dialog, showes informatoin about map object
 *
 * @author pgalex
 */
public class MapObjectInformationDialog extends javax.swing.JDialog
{
	/**
	 * Table model of defenition tags table
	 */
	private DefenitionTagsInformationTableModel defenitionTagsTableModel;

	/**
	 * Create new dialog
	 *
	 * @param parentWindow parent window
	 * @param modalityType modality type of dialog
	 */
	public MapObjectInformationDialog(Window parentWindow, ModalityType modalityType)
	{
		super(parentWindow, modalityType);

		defenitionTagsTableModel = new DefenitionTagsInformationTableModel();

		initComponents();
	}

	/**
	 * Update dailog, showing information about map object
	 *
	 * @param objectToShowInformationAbout map object to show information about
	 * @param objectDrawSettings draw setting of given map object
	 * @throws IllegalArgumentException objectToShowInformationAbout or
	 * objectDrawSettings is null
	 */
	public void showMapObjectInformation(MapObject objectToShowInformationAbout,
					MapObjectDrawSettings objectDrawSettings) throws IllegalArgumentException
	{
		if (objectToShowInformationAbout == null)
		{
			throw new IllegalArgumentException();
		}
		if (objectDrawSettings == null)
		{
			throw new IllegalArgumentException();
		}

		jLabelName.setText(objectDrawSettings.getName());
		jTextAreaDescription.setText(objectDrawSettings.getDescription());
		defenitionTagsTableModel.fillWithDefenitionTags(objectToShowInformationAbout.getDefenitionTags());
	}

	/**
	 * Clear showing information
	 */
	public void clearInformation()
	{
		jLabelName.setText("");
		jTextAreaDescription.setText("");
		defenitionTagsTableModel.setRowCount(0);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabelName = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextAreaDescription = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTableDefenitionTags = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(100, 90));

    jLabelName.setText("<Object Name>");

    jTextAreaDescription.setEditable(false);
    jTextAreaDescription.setBackground(null);
    jTextAreaDescription.setColumns(20);
    jTextAreaDescription.setLineWrap(true);
    jTextAreaDescription.setRows(5);
    jTextAreaDescription.setWrapStyleWord(true);
    jTextAreaDescription.setBorder(null);
    jScrollPane1.setViewportView(jTextAreaDescription);

    jTableDefenitionTags.setModel(defenitionTagsTableModel);
    jScrollPane2.setViewportView(jTableDefenitionTags);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          .add(jLabelName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
          .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLabelName)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabelName;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTableDefenitionTags;
  private javax.swing.JTextArea jTextAreaDescription;
  // End of variables declaration//GEN-END:variables
}
