package com.osmviewer.forms;

import com.osmviewer.mapDefenitionUtilities.Location;
import java.awt.Window;

/**
 * Dialog for asking coordinate to go to
 *
 * @author pgalex
 */
public class GoToCoordinatesDialog extends javax.swing.JDialog
{
	/**
	 * Is go to button pressed (need to move view position)
	 */
	private boolean goToButtonPressed;

	/**
	 * Create new dialog
	 *
	 * @param parentWindow parent window
	 * @param modalityType modality type of dialog
	 * @param initionLocation location to show in dialog after creating
	 */
	public GoToCoordinatesDialog(Window parentWindow, ModalityType modalityType, Location initionLocation)
	{
		super(parentWindow, modalityType);

		if (initionLocation == null)
		{
			throw new IllegalArgumentException("initionLocation is null");
		}

		initComponents();

		setLocationRelativeTo(parentWindow);

		jSpinnerLatitude.setValue(initionLocation.getLatitude());
		jSpinnerLongitude.setValue(initionLocation.getLongitude());
		goToButtonPressed = false;
	}

	/**
	 * Get "go to" location entered throught dialog
	 *
	 * @return "go to" location
	 */
	public Location getGoToLocation()
	{
		return new Location((Double) jSpinnerLatitude.getValue(), (Double) jSpinnerLongitude.getValue());
	}

	/**
	 * Is Go button pressed - need to go to entered coordinates
	 *
	 * @return Is need to go to entered coordinates
	 */
	public boolean isGoToButtonPressed()
	{
		return goToButtonPressed;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    Latitude = new javax.swing.JLabel();
    jLabelLongitude = new javax.swing.JLabel();
    jSpinnerLongitude = new javax.swing.JSpinner();
    jSpinnerLatitude = new javax.swing.JSpinner();
    jButtonGo = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    Latitude.setText("Широта");

    jLabelLongitude.setText("Долгота");

    jSpinnerLongitude.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.1d)));

    jSpinnerLatitude.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.1d)));

    jButtonGo.setText("Перейти");
    jButtonGo.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonGoActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabelLongitude)
              .add(Latitude))
            .add(30, 30, 30)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jSpinnerLatitude, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(jSpinnerLongitude, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
          .add(jButtonGo))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(Latitude, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jSpinnerLatitude))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(jSpinnerLongitude)
          .add(jLabelLongitude, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jButtonGo)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonGoActionPerformed
  {//GEN-HEADEREND:event_jButtonGoActionPerformed
		goToButtonPressed = true;
		setVisible(false);
  }//GEN-LAST:event_jButtonGoActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Latitude;
  private javax.swing.JButton jButtonGo;
  private javax.swing.JLabel jLabelLongitude;
  private javax.swing.JSpinner jSpinnerLatitude;
  private javax.swing.JSpinner jSpinnerLongitude;
  // End of variables declaration//GEN-END:variables
}
